defaults:
  - default
  - _self_

env:
  name: "sumo"
  scenario: "sq2"
  sumo_binary: "sumo"
  sumo_config: "assets/scenarios/SQ2/sq2.sumocfg"
  network_file: "assets/sumo_networks/SQ2/net.net.xml"
  route_file: "assets/scenarios/SQ2/routes.rou.xml"
  episode_horizon: 10800
